! GRID.inc
!
! for /home/lederer/LTRANS/LTRANS_Code_wb/grid_wb.nc

integer, parameter :: ui = 115
integer, parameter :: uj = 257
integer, parameter :: vi = 116
integer, parameter :: vj = 256

integer, parameter :: rho_nodes =  29812
integer, parameter :: u_nodes =    29555
integer, parameter :: v_nodes =    29696

integer, parameter :: max_rho_elements =  29440
integer, parameter :: max_u_elements =    29184
integer, parameter :: max_v_elements =    29325

integer, parameter :: rho_elements =  15079
integer, parameter :: u_elements =    14516
integer, parameter :: v_elements =    14798
